version: '3.8'

services:
  wanderlust:
    build: .
    container_name: wanderlust-app
    ports:
      - "8080:8080"
    environment:
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiaGFyaXNoc2hhcm1hIiwiYSI6ImNtZDdlcTBpejBnZDEyanF2b293Z3ZycTgifQ.EH3KDvvqGRPcgaB0g30Zew
      - MONGODB_URL=mongodb+srv://sharmahani2004_db_user:wanderlust123@cluster0.revl1jc.mongodb.net/wanderlust?retryWrites=true&w=majority
      - CLOUD_NAME=ddcuzulai
      - CLOUD_API_KEY=634663422512837
      - CLOUD_API_SECRET=sjlzAZgFWb6d1j8xjTgxoSDzmfA
      - SECRET=harishsharma
      - PORT=8080
    restart: unless-stopped
    networks:
      - wanderlust-network

networks:
  wanderlust-network:
    driver: bridge